###############################################################################
#
#    Service Config section
#
###############################################################################
server:
  port: "9990,9991"
  mode: debug  # debug;release

###############################################################################
#
#    Nsq Config section
#
###############################################################################
nsq:
  host: "127.0.0.1:4150"
  topic: "send_oneyuan_"
  topic_num : 1

