
### eth_getTransactionByHash
POST https://mainnet.infura.io/1UoO4I
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0x802a072a303a1bb19a20065a262526f2cfda0d1ea16eeb3db6500d9d06f65963"],
    "id":67
}

### eth_getTransactionByHash
POST http://127.0.0.1:8540
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0xf8adc6c73da931dcd046e2b3d00f3359c3e580d4022bbe79f0e9ddfc26db718e"],
    "id":67
}

### eth_getTransactionReceipt
POST https://mainnet.infura.io/1UoO4I
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionReceipt",
    "params":["0x802a072a303a1bb19a20065a262526f2cfda0d1ea16eeb3db6500d9d06f65963"],
    "id":67
}

### eth_getTransactionReceipt
POST http://127.0.0.1:8540
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionReceipt",
    "params":["0x79f5203f0bdeb6cb9392d00c170c1e29a61ed28fcfad6e378524b1b14ae8e60e"],
    "id":67
}


